### ISSUE TITLE
add configuration file and toy dataset to release

### ISSUE THREAD

**Issue by alex-de-zwart** [bolcom/serenade#3]
It would be nice if the configuration file and a small 'toy' dataset could be added to the file with the binary executables. So that all files necessary are available at once and in one place.

**Comment by bkersbergen** [comment]
Thank you Alex.
We now provide example datasets and a configuration files.
Let us know if this work for you.

**Comment by bkersbergen** [comment]
We released a v0.2.0 release and an example project.
