### ISSUE TITLE
expose metrics

### ISSUE THREAD

**Issue by alex-de-zwart** [bolcom/serenade#7]
Is it possible to expose all metrics in serenade for test, when doing hyper param optimization. 
(MRR@20, HR@20, COV@20, POP@20, P@20, R@20)

**Comment by bkersbergen** [comment]
The new version v0.2.6 contains an extra application 'evaluator'
This application can evaluate a testset and reports the prediction metrics and the prediction latency.

Please download the latest release and the updated 'example.zip' file in order to use it.
